services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: taskmanager-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password12*"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql-data: